classdef LpNoiseSource
    %LpNoiseSource generate noise using low passflter
    %   Detailed explanation goes here
    
    properties
        lpFilter
    end
    
    methods
        function obj = LpNoiseSource(sampleRate)
            %LpNioseSource Construct an instance of this class
            %  calculates initial values for the object with a given sample
            %  rate
            oldB = 0.75;
            oldSampleRate = 10000;
            
            f = 1000;
            g = (1 - oldB) / sqrt(1 - 2 * oldB * cos(2 * pi * f / oldSampleRate) + oldB ^ 2);
            extraGain = 2.5 * (sampleRate / 10000) ^ 0.33; 
            
            obj.lpFilter = LpFilter1(sampleRate);
            obj.lpFilter = obj.lpFilter.set(f, g, extraGain);
            
        end
        
        function [obj,outputValue] = getNext(obj)
            %getNext ets the next value generated by the lowpassfilter to
            %be used as a generator using the white noise function 
            x = getWhiteNoise();
            [obj.lpFilter,outputValue] = obj.lpFilter.step(x);
            
        end
    end
end

